plugins {
    id 'multiloader-loader'
    alias(nyfs.plugins.loom)
    alias(nyfs.plugins.mod.publish)
}

configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor(1, "seconds")
}

sourceSets.main.resources { srcDir project(":common").file('src/generated/resources').getAbsolutePath() }

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${nyfs.versions.parchmentMinecraft.get()}:${nyfs.versions.parchmentVersion.get()}@zip")
    }
    modImplementation nyfs.fabric.loader
    modImplementation nyfs.fabric.api
    modApi(nyfs.config.api.fabric)
    include(nyfs.config.api.fabric)
    modImplementation "com.nyfaria.awcapi:awcapi-fabric-${minecraft_version}:${awcapi_version}"
    include "com.nyfaria.awcapi:awcapi-fabric-${minecraft_version}:${awcapi_version}"
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

publishMods {
    file = remapJar.archiveFile
    changelog = project(":common").file("changelog.md").text
    type = STABLE
    modLoaders.add("fabric")
    displayName = "${mod_name}-${minecraft_version}-[Fabric]-${project.version}"
    dryRun = dry_run.toBoolean()
    if (curseforge_publishing_enabled.toBoolean()) {
        curseforge {
            projectId = curseforge_project_id
            accessToken = curseforge_token
            minecraftVersions.add(minecraft_version)
            clientRequired = true
            serverRequired = true
            javaVersions.add(JavaVersion.VERSION_17)
            requires {
                slug = "fabric-api"
            }
        }
    }
    if (modrinth_publishing_enabled.toBoolean()) {
        modrinth {
            accessToken = modrinth_token
            projectId = modrinth_project_id
            minecraftVersions.add(minecraft_version)
            requires {
                slug = "fabric-api"
            }
        }
    }
}