# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.3.0
group=com.nyfaria.nyfsspiders
java_version=21

# Common
minecraft_version=1.21.5
mod_name=Nyf's Spiders
mod_author=Nyfaria
mod_id=nyfsspiders
license=ARR
credits=
description=Vanilla spiders are not yet creepy enough for you? You wish spiders would ?oactually climb properly?r?!\
Nyf's Spiders enables spiders to walk along walls and ceilings and it also improves their AI such that they can find their way around almost any obstacle!
minecraft_version_range=[1.21.5, 1.22)
mappings_channel=parchment
mappings_version=2025.06.15-1.21.5

# Fabric
fabric_version=0.128.2+1.21.5
fabric_loader_version=0.17.2

# NeoForge
neoforge_version=21.5.94
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
forge_config_api_port_version=21.5.1
regutils_version=1.21.3-0.1.0
common_network_version=1.0.18

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=686058
modrinth_publishing_enabled=true
modrinth_project_id=dOGM7ccu
dry_run=false

#org.gradle.configuration-cache=true