# Project
version=3.0.1
group=com.nyfaria
java_version=17

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20, 1.20.2)

# Mod Options
mod_name=Nyf's Spiders
mod_author=Nyfaria
mod_id=nyfsspiders
description=Vanilla spiders are not yet creepy enough for you? You wish spiders would ?oactually climb properly?r?!\
Nyf's Spiders enables spiders to walk along walls and ceilings and it also improves their AI such that they can find their way around almost any obstacle!
license=ARR
credits=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=686058
modrinth_publishing_enabled=true
modrinth_project_id=dOGM7ccu
dry_run=false

awcapi_version=1.0.2