# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Per Project Settings
version=3.0.0
group=com.nyfaria.nyfsspiders
mod_name=Nyf's Spiders
mod_author=Nyfaria
mod_id=nyfsspiders
description=Vanilla spiders are not yet creepy enough for you? You wish spiders would ?oactually climb properly?r?!\
Nyf's Spiders enables spiders to walk along walls and ceilings and it also improves their AI such that they can find their way around almost any obstacle!
credits=

# Dependencies
forge_config_api_port_version=21.11.0
regutils_version=1.21.11-0.1.0
common_network_version=1.0.11

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=686058
modrinth_publishing_enabled=true
modrinth_project_id=dOGM7ccu
dry_run=false


# Common
java_version=25
minecraft_version=26.1-snapshot-2
license=ARR
minecraft_version_range=[26, 27)
neo_form_version=26.1-snapshot-2-1

# Fabric
fabric_version=0.141.2+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.0-alpha.5+snapshot-2
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#org.gradle.configuration-cache=true