plugins {
    id 'multiloader-loader'
    alias(nyfs.plugins.mdg)
    alias(nyfs.plugins.mod.publish)
    alias(nyfs.plugins.hundred.media)
}

configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor(1, "seconds")
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
}

legacyForge {
    version = nyfs.versions.minecraft.get() + "-" + nyfs.versions.forgeVersionNewest.get()
    def at = project(":common").file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at]
    }
    parchment {
        minecraftVersion = nyfs.versions.parchmentMinecraft.get()
        mappingsVersion = nyfs.versions.parchmentVersion.get()
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            jvmArguments =['-XX:+AllowEnhancedClassRedefinition']

        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project(":common").file('src/generated/resources/').getAbsolutePath(), '--existing', rootProject.project(":common").file('src/main/resources/').getAbsolutePath()
        }
    }
}
sourceSets.main.resources { srcDir project(":common").file('src/generated/resources').getAbsolutePath() }


dependencies {
    compileOnly(project(":common"))
    annotationProcessor(nyfs.mixin) {
        artifact {
            classifier = 'processor'
        }
    }
    jarJar(nyfs.mixin.extras.forge)
    modImplementation nyfs.cap.syncer
    jarJar(nyfs.cap.syncer)
    modImplementation(jarJar "com.nyfaria.awcapi:awcapi-neoforge-${minecraft_version}:${awcapi_version}")
}
jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}
publishMods {
    file = jar.archiveFile
    changelog = project(":common").file("changelog.md").text
    type = STABLE
    modLoaders.add("forge")
    displayName = "${mod_name}-${minecraft_version}-[Forge]-${project.version}"
    dryRun = dry_run.toBoolean()
    if (curseforge_publishing_enabled.toBoolean()) {
        curseforge {
            projectId = curseforge_project_id
            accessToken = curseforge_token
            minecraftVersions.add(minecraft_version)
            clientRequired = true
            serverRequired = true
            javaVersions.add(JavaVersion.VERSION_17)
        }
    }
    if (modrinth_publishing_enabled.toBoolean()) {
        modrinth {
            accessToken = modrinth_token
            projectId = modrinth_project_id
            minecraftVersions.add(minecraft_version)
        }
    }
}