plugins {
    id 'multiloader-common'
//    id 'net.neoforged.gradle.userdev' version '7.0.133'
//    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
//    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
//    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'net.neoforged.moddev' version '2.0.107'
}


neoForge {
    neoFormVersion = "1.21.5-20250325.162830"
//    mappings channel: mappings_channel, version: mappings_version
//    version(minecraft_version)
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at.getAbsolutePath()]
    }
}
repositories {
    maven { url "https://maven.fabricmc.net/" }
}
dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${project.forge_config_api_port_version}"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.6"))
    compileOnly("io.github.llamalad7:mixinextras-common:0.3.6")
    implementation "mysticdrew:common-networking-common:${common_network_version}-${minecraft_version}"

}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

